language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "nightly"
install:
  - "python setup.py install"
  - "pip install coveralls"
script: "make test"
after_success: "coveralls"
#notifications:
#  email: false